spring:
  data:
    mongodb:
      uri: mongodb+srv://barbararamos:nqwEkMaNMurGOjZZ@barbarara.fpqhz.mongodb.net/
      database: myDatabase
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG